### ISSUE TITLE
[Enchantement] Proposition for a better look

### ISSUE THREAD

**Issue by Gontier-Julien** [chaotic-aur/chaotic-aur.github.io#8]
I've made some change to the look of the Chaotic aur page and wanted to propose it to you, it also fix some very small issue and should be a little bit more readable.

If you wanted to take a look of it, see the screenshot or see my forked version.

I would be happy to make a pull request if this design is good for you ^^

![Screenshot 2021-06-11 at 18-07-04 Chaotic-AUR automated repo](https://user-images.githubusercontent.com/52894530/121716309-28bea580-cae0-11eb-977b-6f161b3f7c0d.png)
![Screenshot 2021-06-11 at 18-08-26 Chaotic-AUR automated repo](https://user-images.githubusercontent.com/52894530/121716313-29efd280-cae0-11eb-8842-b61c369da86a.png)

**Comment by thotypous** [comment]
Looks nice

**Comment by dr460nf1r3** [comment]
I like it as well, the rounded edges do look indeed very clean :)

**Comment by Gontier-Julien** [comment]
So is it good for me to make a pull request? ^^

**Comment by PedroHLC** [comment]
> So is it good for me to make a pull request? ^^

Sure :wink:

**Comment by Gontier-Julien** [comment]
> > So is it good for me to make a pull request? ^^
> 
> Sure 😉

Okay, I will do it, glad to help a tiny bit on this amazing project that is super useful to the community ^^
